name: CI/CD

on: push

jobs:
  buildtest:
    name: MacOS ${{ matrix.version }} ${{ matrix.compiler }} (with -fsanitize=${{ matrix.sanitizer }})

    strategy:
      fail-fast: false

      matrix:
        version:
          - 12
          - 13
          - 14

        compiler:
          - appleclang-18
          - appleclang-17
          - gcc-13
          - gcc-12
          - gcc-11

        sanitizer:
          - address
          - undefined
          - thread

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build
        run: bash build.sh ${{ matrix.sanitizer }}

      - name: Test
        run: bash test.sh
