name: CI/CD

on: push

jobs:
  buildtest:
    name: ${{ matrix.system.name }} ${{ matrix.compiler }} (with -fsanitize=${{ matrix.sanitize }})

    strategy:
      fail-fast: false

      matrix:
        system:
          - { name: macOS 13,              os: macos-13        }
          - { name: macOS 13 Arm64,        os: macos-13-xlarge }
          - { name: macOS 14,              os: macos-14-large  }
          - { name: macOS 14 Arm64,        os: macos-14        }
          - { name: macOS 15 (beta),       os: macos-15-large  }
          - { name: macOS 15 Arm64 (beta), os: macos-15        }

        compiler:
          - appleclang-19

        sanitize:
          - address
          - undefined
          - thread

    runs-on: ${{ matrix.system.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build
        run: bash build.sh ${{ matrix.sanitize }}

      - name: Test
        run: bash test.sh
