name: CI/CD

on: push

jobs:
  buildtest:
    name: ${{ matrix.system.name }} ${{ matrix.compiler }} (with -fsanitize=${{ matrix.sanitize }})

    strategy:
      fail-fast: false

      matrix:
        system:
          - { name: macOS, os: macos-13, }
          - { name: macOS M1, os: macos-14, }

        compiler:
          - appleclang-18

        sanitize:
          - address
          - undefined
          - thread

    runs-on: ${{ matrix.system.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build
        run: bash build.sh ${{ matrix.sanitize }}

      - name: Test
        run: bash test.sh
