name: CI/CD

on: push

jobs:
  buildtest:
    name: ${{ matrix.system.name }} (with -fsanitize=${{ matrix.sanitize }})

    strategy:
      fail-fast: false

      matrix:
        system:
          - { name: macOS 13,              runner: macos-13 }
          - { name: macOS 14 Arm64,        runner: macos-14 }
          - { name: macOS 15 Arm64 (beta), runner: macos-15 }

        sanitize:
          - address
          - undefined
          - thread

    runs-on: ${{ matrix.system.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: aminya/setup-cpp@v1
        with:
          compiler: appleclang-19

      - name: Build
        run: bash build.sh ${{ matrix.sanitize }}

      - name: Test
        run: bash test.sh
