name: CI/CD

on: push

jobs:
  buildtest:
    name: MacOS ${{ matrix.version }} ${{ matrix.compiler }} (with -fsanitize=${{ matrix.sanitizer }})

    strategy:
      fail-fast: false

      matrix:
        version:
          - 13
          - 14
      
        compiler:
          - clang-18
          - appleclang-18

        sanitizer:
          - address
          - leak
          - undefined
          - thread
          - memory

        exclude:
          # There is no Clang-18 on MacOS-13
          - version: 13
            compiler: clang-18
          # Several of this sanitizers are not presented in MacOS-13 + clang-18
          - version: 13
            sanitizer: leak
          - version: 13
            sanitizer: memory
          # Several of this sanitizers are not presented in MacOS-14
          - version: 14
            sanitizer: memory
          - version: 14
            compiler: appleclang-18
            sanitizer: leak

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build
        run: bash build.sh ${{ matrix.sanitizer }}

      - name: Test
        run: bash test.sh
